// https://vuetifyjs.com/en/features/theme
export const AppLightTheme = {
    dark: false,
    colors: {
        background: '#FFFFFF',
        surface: '#FFFFFF',
        'surface-bright': '#FFFFFF',
        'surface-light': '#EEEEEE',
        'surface-variant': '#424242',
        'on-surface-variant': '#EEEEEE',
        primary: '#fcba03',
        'primary-light': '#ffeb3b',
        'primary-dark': '#c49000',
        'on-primary': '#000000',
        secondary: '#03a9f4',
        'secondary-light': '#67daff',
        'secondary-dark': '#007ac1',
        'on-secondary': '#000000',
        error: '#f44336',
        'error-light': '#ff7961',
        'error-dark': '#ba000d',
        'on-error': '#FFFFFF',
        info: '#2196f3',
        'info-light': '#6ec6ff',
        'info-dark': '#0069c0',
        'on-info': '#FFFFFF',
        success: '#4caf50',
        'success-light': '#81c784',
        'success-dark': '#388e3c',
        'on-success': '#FFFFFF',
        warning: '#ff9800',
        'warning-light': '#ffcc80',
        'warning-dark': '#f57c00',
        'on-warning': '#000000',
        'high-emphasis': '#000000',
        'medium-emphasis': '#000000',
        disabled: '#000000',
        divider: '#000000',
    },
    variables: {
        'border-color': '#000000',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.6,
        'disabled-opacity': 0.38,
        'idle-opacity': 0.04,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'activated-opacity': 0.12,
        'pressed-opacity': 0.12,
        'dragged-opacity': 0.08,
        'theme-kbd': '#212529',
        'theme-on-kbd': '#FFFFFF',
        'theme-code': '#F5F5F5',
        'theme-on-code': '#000000',
    },
};

export default AppLightTheme;
